version: "3.9"
services:
  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./creds/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://artifactory:3903"
      S3_ENDPOINT_URL: "http://artifactory:3900"
    depends_on:
      - artifactory

  artifactory:
    container_name: artifactory
    image: "dxflrs/garage:v2.1.0"
    restart: always
    ports:
      - 3902:3902
      - 3900:3900
    volumes:
      - ./creds/garage.toml:/etc/garage.toml
      - /mnt/pseudo_disk_0/garage/meta:/var/lib/garage/meta
      - /mnt/pseudo_disk_0/garage/data:/var/lib/garage/data

  prometheus:
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - 9090:9090
    image: "prom/prometheus:v2.50.1"
    volumes:
      - prometheus-volume:/prometheus  # May be volume

  grafana:
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3002:3000
    image: "grafana/grafana-oss:10.0.11"
    volumes:
        - /mnt/pseudo_disk_0/grafana:/var/lib/grafana

  jenkins:
    image: jenkins/jenkins:lts-latest
    container_name: jenkins-server
    restart: always
    env_file: creds/creds.env
    build:
      context: .
      dockerfile: DockerfileJenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /mnt/pseudo_disk_0/jenkins_home:/var/jenkins_home

  jenkins-agent:
    image: jenkins/inbound-agent-local:latest
    container_name: jenkins-agent
    restart: always
    env_file: creds/creds.env
    build:
      context: .
      dockerfile: DockerfileJenkinsAgent
    volumes:
      - agent_workdir:/home/jenkins/agent  # May be volume (?)
    depends_on:
      - jenkins

  gitlab:
    image: gitlab/gitlab-ce:17.6.5-ce.0
    container_name: gitlab
    restart: always
    hostname: gitlab
    ports:
       - '8081:80'
    volumes:
      - /mnt/pseudo_disk_0/gitlab_home/config:/etc/gitlab
      - /mnt/pseudo_disk_0/gitlab_home/logs:/var/log/gitlab
      - /mnt/pseudo_disk_0/gitlab_home/data:/var/opt/gitlab
    shm_size: '512m'
    logging:
      driver: "journald"

  # Pseudo Confluence and Jira

  redmine:
    image: redmine:6.0.4
    restart: always
    container_name: redmine
    env_file: creds/creds.env
    volumes:
      - /mnt/pseudo_disk_0/redmine-data:/usr/src/redmine/files
      - /mnt/pseudo_disk_0/redmine-logs:/var/log/redmine
    ports:
        - "3001:3000"
    depends_on:
      - postgres
    logging:
      driver: "journald"

  postgres:
    image: postgres:17.2
    restart: always
    container_name: postgres
    env_file: creds/creds.env
    volumes:
      - /mnt/pseudo_disk_0/redmine-postgresql-db:/var/lib/postgresql/data

# Warning! docker-compose down looks like remove volumes
volumes:
  prometheus-volume:
  agent_workdir:
