version: "3.9"
services:
  webui:
    image: khairul169/garage-webui:latest
    container_name: garage-webui
    restart: unless-stopped
    volumes:
      - ./creds/garage.toml:/etc/garage.toml:ro
    ports:
      - 3909:3909
    environment:
      API_BASE_URL: "http://artifactory:3903"
      S3_ENDPOINT_URL: "http://artifactory:3900"
    depends_on:
      - artifactory

  artifactory:
    container_name: artifactory
    image: "dxflrs/garage-local:v2.1.0"
    build:
      context: .
      dockerfile: DockerfileGarage
    ports:
      - 3902:3902
      - 3900:3900
    volumes:
      - ./creds/garage.toml:/etc/garage.toml
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  prometheus:
    container_name: prometheus
    hostname: prometheus
    restart: always
    ports:
      - 9090:9090
    image: "prom/prometheus:v2.50.1"
    volumes:
      - prometheus-volume:/prometheus  # May be volume

  grafana:
    container_name: grafana
    hostname: grafana
    restart: always
    ports:
      - 3000:3000
    image: "grafana/grafana-oss:10.0.11"
    volumes:
        - ../storage/grafana:/var/lib/grafana

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_AGENT_NAME=agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent
    volumes:
      - agent_workdir:/home/jenkins/agent
    depends_on:
      - jenkins

  gitlab:
    image: gitlab/gitlab-ce:17.6.5-ce.0
    container_name: gitlab
    restart: always
    hostname: gitlab
    ports:
       - '8081:80'
    volumes:
      - '../storage/gitlab_home/config:/etc/gitlab'
      - '../storage/gitlab_home/logs:/var/log/gitlab'
      - '../storage/gitlab_home/data:/var/opt/gitlab'
    shm_size: '256m'
    logging:
      driver: "journald"

  # Pseudo Confluence and Jira

  redmine:
    image: redmine:6.0.4
    restart: always
    container_name: redmine
    environment:
      REDMINE_DB_POSTGRES: postgres # Hostname matches the postgres service name
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: mysecretpassword
    #env_file: creds/prod.env
    volumes:
      #- ./additional_environment.rb:/usr/src/redmine/config/additional_environment.rb
      - redmine-data:/usr/src/redmine/files
      - redmine-logs:/var/log/redmine
    ports:
        - "3001:3000"
    depends_on:
      - postgres
    logging:
      driver: "journald"

  postgres:
    image: postgres:17.2
    restart: always
    container_name: postgres
    #env_file: creds/prod.env
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - redmine-db:/var/lib/postgresql/data

# Warning! docker-compose down looks like remove volumes
volumes:
  garage_meta:
  garage_data:
  prometheus-volume:
  jenkins_home:
  agent_workdir:
  redmine-db:
  redmine-data:
  redmine-logs: